syntax = "proto3";

package messenger;

option java_package = "se.umu.cs.ads.a1.grpc";
option java_multiple_files = true;

// RPC services

service MessengerService {
    rpc ListMessages (ListMessagesRequest) returns (ListMessagesResponse);
    rpc ListMessagesTopic (TopicRequest) returns (ListMessagesResponse);
    rpc Store (StoreRequest) returns (StoreResponse);
    rpc Delete (DeleteRequest) returns (DeleteResponse);
    rpc Retrieve (RetrieveRequest) returns (RetrieveResponse);
    rpc Subscribe (SubscribeRequest) returns (SubscribeResponse);
    rpc Unsubscribe (SubscribeRequest) returns (SubscribeResponse);
    rpc ListUsers (Empty) returns (ListUsersResponse);
    rpc ListTopics (Empty) returns (ListTopicsResponse);
    rpc ListTopicsUser (UserRequest) returns (ListTopicsResponse);
    rpc ListSubscribers (TopicRequest) returns (ListUsersResponse);
}

// new structs

message Msg {
    string messageID = 1;
    int64 timestamp = 2;
    string username = 3;
    string topic = 4;
    string content = 5;
    bytes data = 6;
}

message Empty {}

// Request messages

message StoreRequest {
    Msg message = 1;
}

message DeleteRequest {
    string messageId = 1;
}

message RetrieveRequest{
    string messageId = 1;
}

message SubscribeRequest {
    string username = 1;
    string topic = 2;
}
message ListMessagesRequest {
    string username = 1;
}

message UserRequest {
    string username = 1;
}

message TopicRequest {
    string topic = 1;
}


// Response message
message ListMessagesResponse {
    repeated string messageID = 1;
}


message StoreResponse {
    string response = 1;
}

message DeleteResponse {
    string response = 1;
}

message RetrieveResponse{
    Msg message = 1;
}

message SubscribeResponse {
    repeated string topic = 1;
}

message ListUsersResponse {
    repeated string user = 1;
}

message ListTopicsResponse {
    repeated string topic = 1;
}